# Generated by Django 5.0 on 2024-01-07 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_customuser_followers_alter_blog_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='user_followings', to=settings.AUTH_USER_MODEL),
        ),
    ]
